In [1]:
import numpy as np

In [4]:
scores = np.random.randn(5,3)

In [5]:
print scores

[[-0.45343351  0.35754383 -0.24600149]
 [-0.09186844 -1.02731851 -1.30026764]
 [ 0.61565635  0.60765975  0.9071697 ]
 [-0.6566592   0.22782182 -0.84685839]
 [ 0.42232966 -0.89177159 -0.55126314]]


In [8]:
d = np.argmax(scores,axis=1)

In [9]:
d.shape

(5,)

In [10]:
h1 = np.random.randn(5,10)

In [11]:
w2 = np.random.randn(10,3)

In [14]:
z  = np.dot(h1,w2)

In [15]:
b2 = np.random.randn(3)

In [16]:
z + b2

array([[ 1.12709022,  5.39544491,  4.99995204],
       [ 3.17856881, -1.25707731,  8.9246274 ],
       [-2.79768461, -1.52974435,  2.27148535],
       [ 3.44335035,  1.89575888, -0.33358559],
       [ 4.57061134,  3.01864158,  4.64323457]])

In [17]:
z

array([[ 0.5150994 ,  5.17854572,  3.10005705],
       [ 2.56657799, -1.47397651,  7.02473241],
       [-3.40967544, -1.74664355,  0.37159036],
       [ 2.83135953,  1.67885968, -2.23348058],
       [ 3.95862052,  2.80174238,  2.74333959]])

In [18]:
b2

array([ 0.61199082,  0.2168992 ,  1.89989499])

In [19]:
b2.shape

(3,)